// Generated by scripts/changelog.mjs. Do not edit.
// Every published version of @hzblj/zyplot, parsed out of its CHANGELOG.md.

import type {ChangelogRelease} from './types'

export const CHANGELOG: ChangelogRelease[] = [
  {
    "groups": [
      {
        "entries": [
          {
            "paragraphs": [
              "Add `repository` metadata and a bundled LICENSE file to both published packages. npm verifies a provenance-signed publish against `repository.url`, so the missing field left `@hzblj/zyplot-core` unpublishable."
            ],
            "commit": {
              "href": "https://github.com/hzblj/zyplot/commit/ab6e55e15bcd9bb54e12fedd4981444b13d9e524",
              "sha": "ab6e55e"
            }
          }
        ],
        "label": "Patch Changes"
      }
    ],
    "version": "0.1.1"
  },
  {
    "groups": [
      {
        "entries": [
          {
            "paragraphs": [
              "First public release.",
              "Cross-platform React charting behind one package and one shared TypeScript contract: ECharts and uPlot on web, Swift Charts on iOS, and Jetpack Compose on Android, with both native renderers reached through a single Expo Module named `Zyplot`."
            ],
            "commit": {
              "href": "https://github.com/hzblj/zyplot/commit/51e9ae386cffc75c5d33ab8674905fa5c77c5044",
              "sha": "51e9ae3"
            }
          }
        ],
        "label": "Minor Changes"
      }
    ],
    "version": "0.1.0"
  }
]
