/**
 * Turns the published package's CHANGELOG.md into data the docs can render.
 *
 * The changelog is written by changesets at release time, and the docs page that
 * shows it is a client component — it cannot read the file. Parsing here keeps
 * one source of truth: the release notes a reader sees on the site are the same
 * text npm and the GitHub release carry, with no second copy to update by hand.
 *
 * Two things are dropped on purpose. `Updated dependencies` bullets are the
 * internal core bump, which tells a reader nothing about the package they
 * installed. Dates are not in the file, and the only other place they live is
 * git tags — which a shallow CI clone does not have, so including them would
 * make the output depend on where it was generated.
 */
import {readFileSync, writeFileSync} from 'node:fs'
import {fileURLToPath} from 'node:url'

const CHANGELOG = fileURLToPath(new URL('../../zyplot/CHANGELOG.md', import.meta.url))
const OUTPUT = fileURLToPath(new URL('../src/docs/changelog.generated.ts', import.meta.url))

const VERSION = /^## +(.+?) *$/
const GROUP = /^### +(.+?) *$/
const BULLET = /^- +(.*)$/
/** The commit link changesets puts in front of a note: [`sha`](url) - text */
const COMMIT = /^\[`([^`]+)`\]\(([^)]+)\) *- */

const parse = source => {
  const releases = []
  let release
  let group
  let entry
  /** Set by a blank line: the next text starts a paragraph rather than continuing one. */
  let isBroken = false

  for (const line of source.split('\n')) {
    const version = VERSION.exec(line)

    if (version) {
      release = {groups: [], version: version[1]}
      releases.push(release)
      group = undefined
      entry = undefined
      continue
    }

    const label = GROUP.exec(line)

    if (label && release) {
      group = {entries: [], label: label[1]}
      release.groups.push(group)
      entry = undefined
      continue
    }

    if (!group) {
      continue
    }

    const bullet = BULLET.exec(line)

    if (bullet) {
      entry = undefined

      if (bullet[1].startsWith('Updated dependencies')) {
        continue
      }

      const commit = COMMIT.exec(bullet[1])
      entry = {paragraphs: []}
      group.entries.push(entry)

      if (commit) {
        entry.commit = {href: commit[2], sha: commit[1]}
      }

      const text = bullet[1].replace(COMMIT, '').trim()

      if (text) {
        entry.paragraphs.push(text)
      }

      isBroken = false
      continue
    }

    if (!line.trim()) {
      isBroken = true
      continue
    }

    // Anything else indented under a bullet is that note continuing: changesets
    // hard-wraps prose, so a paragraph arrives as several lines.
    if (entry && line.startsWith(' ')) {
      const text = line.trim()

      if (isBroken || entry.paragraphs.length === 0) {
        entry.paragraphs.push(text)
      } else {
        entry.paragraphs[entry.paragraphs.length - 1] += ` ${text}`
      }

      isBroken = false
    }
  }

  return releases.map(item => ({
    ...item,
    groups: item.groups.filter(candidate => candidate.entries.length > 0),
  }))
}

const releases = parse(readFileSync(CHANGELOG, 'utf8'))

const header = `// Generated by scripts/changelog.mjs. Do not edit.
// Every published version of @hzblj/zyplot, parsed out of its CHANGELOG.md.

import type {ChangelogRelease} from './types'

`

writeFileSync(OUTPUT, `${header}export const CHANGELOG: ChangelogRelease[] = ${JSON.stringify(releases, null, 2)}\n`)

console.log(`Wrote ${releases.length} releases to changelog.generated.ts`)
