import {readFileSync, writeFileSync} from 'node:fs'
import {fileURLToPath} from 'node:url'
import {createHighlighter} from 'shiki'
import ts from 'typescript'

const DOC_FILES = [
  fileURLToPath(new URL('../src/docs/chart-docs.tsx', import.meta.url)),
  fileURLToPath(new URL('../src/docs/guide-content.tsx', import.meta.url)),
]
const CHART_CODE = fileURLToPath(new URL('../src/docs/chart-code.ts', import.meta.url))
const INSTALL_COMMANDS = fileURLToPath(new URL('../src/install-commands.ts', import.meta.url))
const OUTPUT = fileURLToPath(new URL('../src/docs/highlighted-samples.generated.ts', import.meta.url))
const THEMES = {dark: 'night-owl', light: 'night-owl-light'}
const LANGUAGES = ['bash', 'css', 'json', 'ts', 'tsx']

const importPlainModule = async path => {
  const {outputText} = ts.transpileModule(readFileSync(path, 'utf8'), {
    compilerOptions: {module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ESNext},
  })
  const encoded = Buffer.from(outputText).toString('base64')
  return import(`data:text/javascript;base64,${encoded}`)
}

const literalText = node =>
  node && (ts.isNoSubstitutionTemplateLiteral(node) || ts.isStringLiteral(node)) ? node.text : undefined

const collectSamples = (path, chartExample) => {
  const source = readFileSync(path, 'utf8')
  const tree = ts.createSourceFile(path, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX)
  const samples = []
  const literals = new Map()

  const collectLiteral = node => {
    if (ts.isVariableDeclaration(node) && ts.isIdentifier(node.name)) {
      const value = literalText(node.initializer)
      if (value !== undefined) {
        literals.set(node.name.text, value)
      }
    }
    ts.forEachChild(node, collectLiteral)
  }

  collectLiteral(tree)

  const resolveText = node => {
    const direct = literalText(node)
    return direct ?? (node && ts.isIdentifier(node) ? literals.get(node.text) : undefined)
  }

  const visit = node => {
    if (ts.isJsxElement(node) && node.openingElement.tagName.getText() === 'CodeBlock') {
      const language =
        node.openingElement.attributes.properties
          .filter(ts.isJsxAttribute)
          .find(attribute => attribute.name.getText() === 'language')?.initializer?.text ?? 'tsx'

      for (const child of node.children) {
        const code = ts.isJsxExpression(child) ? literalText(child.expression) : undefined
        if (code !== undefined) {
          samples.push({code, language, origin: 'CodeBlock'})
        }
      }
    }

    if (ts.isJsxSelfClosingElement(node) && node.tagName.getText() === 'AppGuide') {
      const codeAttribute = node.attributes.properties
        .filter(ts.isJsxAttribute)
        .find(attribute => attribute.name.getText() === 'code')
      const expression =
        codeAttribute?.initializer && ts.isJsxExpression(codeAttribute.initializer)
          ? codeAttribute.initializer.expression
          : undefined
      const code = resolveText(expression)
      if (code !== undefined) {
        samples.push({code, language: 'tsx', origin: 'AppGuide'})
      }
    }

    if (ts.isCallExpression(node) && ['chartExample', 'code'].includes(node.expression.getText())) {
      const [name, body, setup, entryPoint] = node.arguments.map(resolveText)
      if (name !== undefined && body !== undefined) {
        samples.push({
          code: chartExample(name, body, setup, entryPoint),
          language: 'tsx',
          origin: `chartExample(${name})`,
        })
      }
    }

    ts.forEachChild(node, visit)
  }

  visit(tree)
  return samples
}

const {chartExample} = await importPlainModule(CHART_CODE)
const {INSTALL_COMMANDS: installCommands} = await importPlainModule(INSTALL_COMMANDS)

const samples = [
  ...DOC_FILES.flatMap(path => collectSamples(path, chartExample)),
  ...Object.entries(installCommands).map(([manager, code]) => ({
    code,
    language: 'bash',
    origin: `install(${manager})`,
  })),
]

if (samples.length === 0) {
  throw new Error('No code samples found in the documentation source files.')
}

const languageFor = new Map()
for (const {code, language, origin} of samples) {
  const existing = languageFor.get(code)
  if (existing && existing.language !== language) {
    throw new Error(
      `The same sample is used as both ${existing.language} and ${language} ` +
        `(${existing.origin} vs ${origin}). Keying by source text cannot represent that.`
    )
  }
  languageFor.set(code, {language, origin})
}

const highlighter = await createHighlighter({langs: LANGUAGES, themes: [THEMES.dark, THEMES.light]})

const entries = [...languageFor].map(([code, {language}]) => {
  const html = highlighter.codeToHtml(code, {
    defaultColor: 'light',
    lang: LANGUAGES.includes(language) ? language : 'text',
    themes: THEMES,
  })
  return `  ${JSON.stringify(code)}: ${JSON.stringify(html)},`
})

writeFileSync(
  OUTPUT,
  `// Generated by scripts/highlight-samples.mjs. Do not edit.

export const HIGHLIGHTED_SAMPLES: Record<string, string> = {
${entries.join('\n')}
}
`
)

const KINDS = {chartExample: 'chart examples', install: 'install commands'}

const byOrigin = samples.reduce((counts, {origin}) => {
  const kind = Object.entries(KINDS).find(([prefix]) => origin.startsWith(prefix))?.[1] ?? 'inline blocks'
  return {...counts, [kind]: (counts[kind] ?? 0) + 1}
}, {})

console.log(`highlighted ${languageFor.size} samples (${JSON.stringify(byOrigin)}) → ${OUTPUT.split('/').pop()}`)
